#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vi=vim

if (( $+commands[ccat] )); then
  alias cat=ccat
fi

if (( $+commands[jenv] )); then
  source <(jenv init -)
fi

if [[ -f "${HOME}/.iterm2_shell_integration.zsh" ]]; then
  source "${HOME}/.iterm2_shell_integration.zsh"
fi

if [[ -d "/usr/local/Caskroom/google-cloud-sdk" ]]; then
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
fi

if (( $+commands[kubectl] )); then
  source <(kubectl completion zsh)
fi

if [[ -d $(brew --prefix nvm) ]]; then
  source $(brew --prefix nvm)/nvm.sh
fi
